### ISSUE TITLE
Rename feat/ogl to dev/globjects?

### ISSUE THREAD

**Issue by ecumene-software** [team-joogl/joogl#5]
Title said it all, should we rename the branch? If we keep it this way forever I'm only going to commit to this branch xD

**Comment by zgoethel12** [comment]
Sounds good, unless you want xxxx/ogl/objects or something

**Comment by ecumene-software** [comment]
eh, then it's still got the ogl thing. OpenGL is the core of this library, I think the gl is enough... I'll do that now
