### ISSUE TITLE
Game loop code spams new GLFWWindows

### ISSUE THREAD

**Issue by zgoethel12** [team-joogl/joogl#6]
I have decided to implement joogle into a new project I'm working on, so I have written some basic code to manage a GLFWWindow.  The code is below, and once you start running it GLFWWindows start spamming on the screen.

	package dungeon;
	
	import org.lwjgl.opengl.GLContext;
	
	import joogl.SharedLibraryLoader;
	import joogl.glfw.GLFWWindow;
	import joogl.glfw.GLFWWindowContainer;
	import joogl.glfw.GLFWWindows;
	
	/**
	 * @author Zach Goethel
	 */
	public class Dungeon
	{
		public GLFWWindow window;
		
		public void setup()
		{
			
		}
		
		public void update()
		{
			
		}
		
		public void render()
		{
			
		}
		
		public void destroy()
		{
			
		}
		
		public static Dungeon dungeon;
		
		public static synchronized void setupGraphicsContext()
		{
			SharedLibraryLoader.load();
			GLFWWindows.init();
		}
		
		public static synchronized void destroyGraphicsContext()
		{
			GLFWWindows.terminate();
		}
		
		public static synchronized void setupGameLoop(Dungeon dungeon)
		{
			dungeon.window = new GLFWWindowContainer(GLFWWindows.createWindow(800, 450, "Dungeon", 0L, 0L));
			GLFWWindows.makeContextCurrent(dungeon.window);
			GLContext.createFromCurrent();
			dungeon.setup();
		}
		
		public static synchronized void destroyGameLoop(Dungeon dungeon)
		{
			dungeon.destroy();
			((GLFWWindowContainer)dungeon.window).destroy();
		}
		
		public static void beginGameLoop(Dungeon dungeon)
		{
			setupGameLoop(dungeon);
			
			while (!((GLFWWindowContainer)dungeon.window).shouldClose())
			{
				dungeon.update();
				GLFWWindows.makeContextCurrent(dungeon.window);
				dungeon.render();
				((GLFWWindowContainer)dungeon.window).swapBuffers();
			}
			
			destroyGameLoop(dungeon);
		}
		
		public static void main(String[] args)
		{
			dungeon = new Dungeon();
			setupGraphicsContext();
			beginGameLoop(dungeon);
			destroyGraphicsContext();
		}
	}

**Comment by ecumene-software** [comment]
It was doing the same for me, I thought it was JUnit... I'll look into it :O

**Comment by ecumene-software** [comment]
It may be because you don't have default-hints (or hints in general) setup. I tried to set them up and run then it crashed gnome ;( 

For the record if I had a nickel every time gnome crashed I could buy windows, so I'm not surprised.

**Comment by ecumene-software** [comment]
I won't label this as a bug though, these are standard GLFW calls...

**Comment by zgoethel12** [comment]
Adding `GLFWWindows.defaultWindowHints();` directly after `dungeon.window = new GLFWWindowContainer(GLFWWindows.createWindow(800, 450, "Dungeon", 0L, 0L));` made no difference.  Perhaps I put it in the wrong place, or I'm missing an element completely, or there is really something wrong with the internals.

**Comment by ecumene-software** [comment]
The design of this library is that if I just wrap all OpenGL/GLFW functions completely there's no room for error and I can just sit back and say "Wasn't me!"

`GLFWWindows.defaultWindowHints();` should go before `GLFWWindows.createWindow`.

Also it seems `GLFWWindowContainer.swapBuffers` is the culprit, I put a delay and it's creating a window every 1 second now. o.O

**Comment by zgoethel12** [comment]
I found that any call to GLFW duplicated the window.  I had to comment out every single one, including `.shouldClose()', and even moved `.defaultWindowHints()' before `.createWindow()`.  Nothing has changed.

**Comment by ecumene-software** [comment]
Is there a "panic" label? :O

**Comment by ecumene-software** [comment]
Oh I know why. `GLFWWindow.getWindow` is pointing to `GLFWWindows.createWindow`

Hello darkness my old friend

**Comment by zgoethel12** [comment]
This is the `.createWindow()` code:

    public static synchronized GLFWWindow createWindow(int width, int height, String title, long monitor, long share) {
        return () -> GLFW.glfwCreateWindow(width, height, title, monitor, share);
    }

It makes the method point to `.glfwCreateWindow()`, so every time you call `.getWindow()` or whatever it creates a new one.

**Comment by zgoethel12** [comment]
Dang!

**Comment by ecumene-software** [comment]
I beat you to it HAH!

**Comment by zgoethel12** [comment]
It took me longer because I was looking for a constructor instead of a method... heh

**Comment by ecumene-software** [comment]
I'll fix the createWindow method, merge and delete this. I wonder how github handles merging with issues.

**Comment by zgoethel12** [comment]
How does one... merge an issue... and with what

**Comment by ecumene-software** [comment]
Merge a change to a branch while it gets logged in an issue, it just makes it look professional. (Like a nice suite, or a tonne of branches everywhere)

**Comment by zgoethel12** [comment]
I wrote this snippet, and it seems to work.  Want me to commit it?
    public static synchronized GLFWWindow createWindow(int width, int height, String title, long monitor, long share) {
        long window = GLFW.glfwCreateWindow(width, height, title, monitor, share);
    	return () -> { return window; };
    }

**Comment by ecumene-software** [comment]
I just did the same thing actually! It's merged. You closed it before I could merge & attach it to this issue ;(

**Comment by ecumene-software** [comment]
Fixed in #7, (that's pretty underwhelming) no need to reopen it I guess
