### ISSUE TITLE
Remove lambdas for better Java version support?

### ISSUE THREAD

**Issue by zgoethel12** [team-joogl/joogl#8]
I know you are in love with lambdas, and I enjoy using them too.  However, most people are not working in Java 8 and would like their projects to be useful to other people who are working with earlier Java versions.

**Comment by ecumene-software** [comment]
I don't think I know anyone not using java 8, language support is really just a personal thing...

**Comment by zgoethel12** [comment]
Distributing a product to customers who don't have Java 8 would be difficult, as not even all of my house's computers have Java 8.  My mom's laptop has Java 7, the tower probably has 8, my laptop has 8, an the iMac we ditched ASAP had only support for 6.  We should at least try to support as low as 6.

**Comment by zgoethel12** [comment]
I just want your permission to go ahead and replace the lambdas, I can do it myself.

**Comment by ecumene-software** [comment]
Okay 6 it is but I'm going to be saucy over installing openjdk 6 on my desktop :(

**Comment by zgoethel12** [comment]
That's fine, thank you.
