### ISSUE TITLE
Renaming the repo + project

### ISSUE THREAD

**Issue by ecumene-software** [team-joogl/joogl#9]
A few people on java-gaming.org said it's too close to JOGL. I think it's just fine... But if we can find a good name that'd be even better!

**Comment by zgoethel12** [comment]
I like that it's close to JOGL.  I am open to new ideas, however.  I'll keep thinking!

**Comment by zgoethel12** [comment]
Where's the java-gaming.org page?

**Comment by ecumene-software** [comment]
I guess it's unanimous 2/2 votes :) I'll do that tonight. What should the name be?

**Comment by zgoethel12** [comment]
We could go with something cute, or a play on words, or a cold tech-sounding name.  OOGRE (I know, it's bad, but let's get the juices flowing)

**Comment by ecumene-software** [comment]
http://www.ogre3d.org/ :persecutioncomplex:

**Comment by zgoethel12** [comment]
I knew ogre existed, I don't even know why I recommended that name XD  What about something that plays on the world "wrap"

**Comment by ecumene-software** [comment]
JSwatheGL, JSwaddleGL?

**Comment by zgoethel12** [comment]
My mind is going McWrap so hard right now...

**Comment by ecumene-software** [comment]
Ah yes the 1/2 a pound concoction of "probably chicken"

**Comment by zgoethel12** [comment]
Enveloop, foolder (I'm on the thesaurus page for wrapper)

**Comment by zgoethel12** [comment]
AH!  JGarment (just kidding)

**Comment by ecumene-software** [comment]
How about JOOG: Java Object Oriented openGl or JGOO?

**Comment by zgoethel12** [comment]
GLoom?

**Comment by ecumene-software** [comment]
What's the M for?

**Comment by zgoethel12** [comment]
To make the word gloom make sense, I guess

**Comment by ecumene-software** [comment]
I kinda like it.. How about jgloom? It'll make it show up on google better. Also it's not already a library

**Comment by zgoethel12** [comment]
jGLoom, JGLoom, jGLOOm, how do you want to capitalize?  I like it too.  jGLOOm looks kinda good with the GLOO in the middle

**Comment by ecumene-software** [comment]
JGLOOm Cause the m is not a part of the acronym

**Comment by zgoethel12** [comment]
What's GREAT about a design like this is you (maybe) would be able to not only wrap OpenGL but something like Vulkan (if a Java port ever comes around) with minimally modified code for users of the library.  I'm not saying that should be a design choice we make, but it would be neat.

**Comment by ecumene-software** [comment]
LWJGL has a vulkan binding on the way, and there's a few demos on JGO :D

**Comment by ecumene-software** [comment]
I'll rename it, you might want to commit any changes and rename the folder and change the remote entry in `.git/config`

**Comment by zgoethel12** [comment]
Okay, pull the lever Kronk!

**Comment by zgoethel12** [comment]
The M could mean Maven

**Comment by zgoethel12** [comment]
Or manager, if you really want it in the acronym

**Comment by ecumene-software** [comment]
I was thinking Java openGL: Object Oriented (man!)
